### ISSUE TITLE
bootstrap version? copared with formo?

### ISSUE THREAD

**Issue by rakucmr** [davidstutz/kohana-gaps#1]
1. what version of bootstrap are you using?
2. is kohana-gaps better than kohana-formo?

**Comment by davidstutz** [comment]
Initially I used `2.3.x`, but it should easily be updated to `3.x`. I would not say it is better - it is different. Originally I used kohana-formo myselft, but I ended up coding kohana-gaps because it fits my needs better.

Sorry for the late answer ;)
